using System.Collections.Generic;

namespace DataFactory
{
    public static class Data
    {
        public static readonly string[] PostcodeAlpha = { "A", "B", "D", "E", "F", "G", "H", "L", "N", "P", "R", "S", "T", "U", "W", "X", "Y" };
        public static readonly string[] LoremWords = { "consetetur", "sadipscing", "elitr", "sed", "diam", "nonumy", "eirmod", "tempor", "invidunt", "ut", "labore", "et", "dolore", "magna", "aliquyam", "erat", "sed", "diam", "voluptua", "at", "vero", "eos", "et", "accusam", "et", "justo", "duo", "dolores", "et", "ea", "rebum", "stet", "clita", "kasd", "gubergren", "no", "sea", "takimata", "sanctus", "est", "lorem", "ipsum", "dolor", "sit", "amet", "lorem", "ipsum", "dolor", "sit", "amet", "consetetur", "sadipscing", "elitr", "sed", "diam", "nonumy", "eirmod", "tempor", "invidunt", "ut", "labore", "et", "dolore", "magna", "aliquyam", "erat", "sed", "diam", "voluptua", "at", "vero", "eos", "et", "accusam", "et", "justo", "duo", "dolores", "et", "ea", "rebum", "stet", "clita", "kasd", "gubergren", "no", "sea", "takimata", "sanctus", "est", "lorem", "ipsum", "dolor", "sit", "amet", "lorem", "ipsum", "dolor", "sit", "amet", "consetetur", "sadipscing", "elitr", "sed", "diam", "nonumy", "eirmod", "tempor", "invidunt", "ut", "labore", "et", "dolore", "magna", "aliquyam", "erat", "sed", "diam", "voluptua", "at", "vero", "eos", "et", "accusam", "et", "justo", "duo", "dolores", "et", "ea", "rebum", "stet", "clita", "kasd", "gubergren", "no", "sea", "takimata", "sanctus", "est", "lorem", "ipsum", "dolor", "sit", "amet", "duis", "autem", "vel", "eum", "iriure", "dolor", "in", "hendrerit", "in", "vulputate", "velit", "esse", "molestie", "consequat", "vel", "illum", "dolore", "eu", "feugiat", "nulla", "facilisis", "at", "vero", "eros", "et", "accumsan", "et", "iusto", "odio", "dignissim", "qui", "blandit", "praesent", "luptatum", "zzril", "delenit", "augue", "duis", "dolore", "te", "feugait", "nulla", "facilisi", "lorem", "ipsum", "dolor", "sit", "amet", "consectetuer", "adipiscing", "elit", "sed", "diam", "nonummy", "nibh", "euismod", "tincidunt", "ut", "laoreet", "dolore", "magna", "aliquam", "erat", "volutpat", "ut", "wisi", "enim", "ad", "minim", "veniam", "quis", "nostrud", "exerci", "tation", "ullamcorper", "suscipit", "lobortis", "nisl", "ut", "aliquip", "ex", "ea", "commodo", "consequat", "duis", "autem", "vel", "eum", "iriure", "dolor", "in", "hendrerit", "in", "vulputate", "velit", "esse", "molestie", "consequat", "vel", "illum", "dolore", "eu", "feugiat", "nulla", "facilisis", "at", "vero", "eros", "et", "accumsan", "et", "iusto", "odio", "dignissim", "qui", "blandit", "praesent", "luptatum", "zzril", "delenit", "augue", "duis", "dolore", "te", "feugait", "nulla", "facilisi", "nam", "liber", "tempor", "cum", "soluta", "nobis", "eleifend", "option", "congue", "nihil", "imperdiet", "doming", "id", "quod", "mazim", "placerat", "facer", "possim", "assum", "lorem", "ipsum", "dolor", "sit", "amet", "consectetuer", "adipiscing", "elit", "sed", "diam", "nonummy", "nibh", "euismod", "tincidunt", "ut", "laoreet", "dolore", "magna", "aliquam", "erat", "volutpat", "ut", "wisi", "enim", "ad", "minim", "veniam", "quis", "nostrud", "exerci", "tation", "ullamcorper", "suscipit", "lobortis", "nisl", "ut", "aliquip", "ex", "ea", "commodo", "consequat", "duis", "autem", "vel", "eum", "iriure", "dolor", "in", "hendrerit", "in", "vulputate", "velit", "esse", "molestie", "consequat", "vel", "illum", "dolore", "eu", "feugiat", "nulla", "facilisis", "at", "vero", "eos", "et", "accusam", "et", "justo", "duo", "dolores", "et", "ea", "rebum", "stet", "clita", "kasd", "gubergren", "no", "sea", "takimata", "sanctus", "est", "lorem", "ipsum", "dolor", "sit", "amet", "lorem", "ipsum", "dolor", "sit", "amet", "consetetur", "sadipscing", "elitr", "sed", "diam", "nonumy", "eirmod", "tempor", "invidunt", "ut", "labore", "et", "dolore", "magna", "aliquyam", "erat", "sed", "diam", "voluptua", "at", "vero", "eos", "et", "accusam", "et", "justo", "duo", "dolores", "et", "ea", "rebum", "stet", "clita", "kasd", "gubergren", "no", "sea", "takimata", "sanctus", "est", "lorem", "ipsum", "dolor", "sit", "amet", "lorem", "ipsum", "dolor", "sit", "amet", "consetetur", "sadipscing", "elitr", "at", "accusam", "aliquyam", "diam", "diam", "dolore", "dolores", "duo", "eirmod", "eos", "erat", "et", "nonumy", "sed", "tempor", "et", "et", "invidunt", "justo", "labore", "stet", "clita", "ea", "et", "gubergren", "kasd", "magna", "no", "rebum", "sanctus", "sea", "sed", "takimata", "ut", "vero", "voluptua", "est", "lorem", "ipsum", "dolor", "sit", "amet", "lorem", "ipsum", "dolor", "sit", "amet", "consetetur", "sadipscing", "elitr", "sed", "diam", "nonumy", "eirmod", "tempor", "invidunt", "ut", "labore", "et", "dolore", "magna", "aliquyam", "erat", "consetetur", "sadipscing", "elitr", "sed", "diam", "nonumy", "eirmod", "tempor", "invidunt", "ut", "labore", "et", "dolore", "magna", "aliquyam", "erat", "sed", "diam", "voluptua", "at", "vero", "eos", "et", "accusam", "et", "justo", "duo", "dolores", "et", "ea", "rebum", "stet", "clita", "kasd", "gubergren", "no", "sea", "takimata", "sanctus", "est", "lorem", "ipsum" };
        public static readonly Dictionary<string, string> TownsAndCounties = new Dictionary<string, string> {
            { "Ampthill","Bedfordshire"},
            { "Arlesey","Bedfordshire"},
            { "Bedford","Bedfordshire"},
            { "Biggleswade","Bedfordshire"},
            { "Dunstable","Bedfordshire"},
            { "Flitwick","Bedfordshire"},
            { "Houghton Regis","Bedfordshire"},
            { "Kempston","Bedfordshire"},
            { "Leighton Buzzard","Bedfordshire"},
            { "Linslade","Bedfordshire"},
            { "Luton","Bedfordshire"},
            { "Potton","Bedfordshire"},
            { "Sandy","Bedfordshire"},
            { "Shefford","Bedfordshire"},
            { "Stotfold","Bedfordshire"},
            { "Wixams","Bedfordshire"},
            { "Woburn","Bedfordshire"},
            { "Ascot","Berkshire"},
            { "Bracknell","Berkshire"},
            { "Crowthorne","Berkshire"},
            { "Earley","Berkshire"},
            { "Eton","Berkshire"},
            { "Hungerford","Berkshire"},
            { "Lambourn","Berkshire"},
            { "Maidenhead","Berkshire"},
            { "Newbury","Berkshire"},
            { "Reading","Berkshire"},
            { "Sandhurst","Berkshire"},
            { "Slough","Berkshire"},
            { "Thatcham","Berkshire"},
            { "Windsor","Berkshire"},
            { "Wokingham","Berkshire"},
            { "Woodley","Berkshire"},
            { "Bristol","Bristol"},
            { "Amersham","Buckinghamshire"},
            { "Aylesbury","Buckinghamshire"},
            { "Beaconsfield","Buckinghamshire"},
            { "Bletchley","Buckinghamshire"},
            { "Buckingham","Buckinghamshire"},
            { "Chesham","Buckinghamshire"},
            { "Fenny Stratford","Buckinghamshire"},
            { "High Wycombe","Buckinghamshire"},
            { "Marlow","Buckinghamshire"},
            { "Milton Keynes","Buckinghamshire"},
            { "Newport Pagnell","Buckinghamshire"},
            { "Olney","Buckinghamshire"},
            { "Princes Risborough","Buckinghamshire"},
            { "Stony Stratford","Buckinghamshire"},
            { "Wendover","Buckinghamshire"},
            { "Winslow","Buckinghamshire"},
            { "Woburn Sands","Buckinghamshire"},
            { "Wolverton and Greenleys","Buckinghamshire"},
            { "Cambridge","Cambridgeshire"},
            { "Chatteris","Cambridgeshire"},
            { "Ely","Cambridgeshire"},
            { "Fulbourn","Cambridgeshire"},
            { "Godmanchester","Cambridgeshire"},
            { "Hanley Grange","Cambridgeshire"},
            { "Huntingdon","Cambridgeshire"},
            { "March","Cambridgeshire"},
            { "Northstowe","Cambridgeshire"},
            { "Peterborough","Cambridgeshire"},
            { "Ramsey","Cambridgeshire"},
            { "Soham","Cambridgeshire"},
            { "St Ives","Cambridgeshire"},
            { "St Neots","Cambridgeshire"},
            { "Whittlesey","Cambridgeshire"},
            { "Wisbech","Cambridgeshire"},
            { "Alsager","Cheshire"},
            { "Birchwood","Cheshire"},
            { "Bollington","Cheshire"},
            { "Chester","Cheshire"},
            { "Congleton","Cheshire"},
            { "Crewe","Cheshire"},
            { "Ellesmere Port","Cheshire"},
            { "Frodsham","Cheshire"},
            { "Knutsford","Cheshire"},
            { "Macclesfield","Cheshire"},
            { "Malpas","Cheshire"},
            { "Middlewich","Cheshire"},
            { "Nantwich","Cheshire"},
            { "Neston","Cheshire"},
            { "Northwich","Cheshire"},
            { "Poynton with Worth","Cheshire"},
            { "Runcorn","Cheshire"},
            { "Sandbach","Cheshire"},
            { "Warrington","Cheshire"},
            { "Widnes","Cheshire"},
            { "Wilmslow","Cheshire"},
            { "Winsford","Cheshire"},
            { "Bodmin","Cornwall"},
            { "Bude","Cornwall"},
            { "Callington","Cornwall"},
            { "Camborne","Cornwall"},
            { "Camelford","Cornwall"},
            { "Charlestown","Cornwall"},
            { "Falmouth","Cornwall"},
            { "Fowey","Cornwall"},
            { "Hayle","Cornwall"},
            { "Helston","Cornwall"},
            { "Launceston","Cornwall"},
            { "Liskeard","Cornwall"},
            { "Looe","Cornwall"},
            { "Lostwithiel","Cornwall"},
            { "Marazion","Cornwall"},
            { "Newlyn","Cornwall"},
            { "Newquay","Cornwall"},
            { "Padstow","Cornwall"},
            { "Par","Cornwall"},
            { "Penryn","Cornwall"},
            { "Penzance","Cornwall"},
            { "Porthleven","Cornwall"},
            { "Redruth","Cornwall"},
            { "Saltash","Cornwall"},
            { "St Austell","Cornwall"},
            { "St Blazey","Cornwall"},
            { "St Columb Major","Cornwall"},
            { "St Just","Cornwall"},
            { "St Mawes","Cornwall"},
            { "Stratton","Cornwall"},
            { "Torpoint","Cornwall"},
            { "Truro","Cornwall"},
            { "Wadebridge","Cornwall"},
            { "Barnard Castle","Cornwall"},
            { "Billingham","County Durham"},
            { "Bishop Auckland","County Durham"},
            { "Chester le Street","County Durham"},
            { "Consett","County Durham"},
            { "Crook","County Durham"},
            { "Darlington","County Durham"},
            { "Durham","County Durham"},
            { "Eaglescliffe","County Durham"},
            { "Eastington","County Durham"},
            { "Ferryhill","County Durham"},
            { "Greater Willington","County Durham"},
            { "Hartlepool","County Durham"},
            { "Newton Aycliffe","County Durham"},
            { "Peterlee","County Durham"},
            { "Seaham","County Durham"},
            { "Sedgefield","County Durham"},
            { "Shildon","County Durham"},
            { "Spennymoor","County Durham"},
            { "Stanhope","County Durham"},
            { "Stanley","County Durham"},
            { "Stockton on Tees","County Durham"},
            { "Tow Law","County Durham"},
            { "Willington","County Durham"},
            { "Wolsingham","County Durham"},
            { "Alston","County Durham"},
            { "Ambleside","Cumbria"},
            { "Appleby in Westmorland","Cumbria"},
            { "Aspatria","Cumbria"},
            { "Barrow in Furness","Cumbria"},
            { "Bowness on Windermere","Cumbria"},
            { "Brampton","Cumbria"},
            { "Broughton in Furness","Cumbria"},
            { "Carlisle","Cumbria"},
            { "Cleator Moor","Cumbria"},
            { "Cockermouth","Cumbria"},
            { "Dalton in Furness","Cumbria"},
            { "Egremont","Cumbria"},
            { "Grange over Sands","Cumbria"},
            { "Harrington","Cumbria"},
            { "Kendal","Cumbria"},
            { "Keswick","Cumbria"},
            { "Kirkby Lonsdale","Cumbria"},
            { "Kirkby Stephen","Cumbria"},
            { "Longtown","Cumbria"},
            { "Maryport","Cumbria"},
            { "Millom","Cumbria"},
            { "Milnthorpe","Cumbria"},
            { "Orgill","Cumbria"},
            { "Penrith","Cumbria"},
            { "Sedbergh","Cumbria"},
            { "Silloth","Cumbria"},
            { "Staveley","Cumbria"},
            { "Ulverston","Cumbria"},
            { "Whitehaven","Cumbria"},
            { "Wigton","Cumbria"},
            { "Windermere","Cumbria"},
            { "Workington","Cumbria"},
            { "Alfreton","Cumbria"},
            { "Ashbourne","Derbyshire"},
            { "Bakewell","Derbyshire"},
            { "Barrow Hill and Whittington","Derbyshire"},
            { "Belper","Derbyshire"},
            { "Bolsover","Derbyshire"},
            { "Buxton","Derbyshire"},
            { "Chapel en le Frith","Derbyshire"},
            { "Chesterfield","Derbyshire"},
            { "Clay Cross","Derbyshire"},
            { "Darley Dale","Derbyshire"},
            { "Derby","Derbyshire"},
            { "Dronfield","Derbyshire"},
            { "Dronfield Woodhouse","Derbyshire"},
            { "Eckington","Derbyshire"},
            { "Fairfield","Derbyshire"},
            { "Glossop","Derbyshire"},
            { "Hadfield","Derbyshire"},
            { "Heanor","Derbyshire"},
            { "Ilkeston","Derbyshire"},
            { "Killamarsh","Derbyshire"},
            { "Langley Mill","Derbyshire"},
            { "Long Eaton","Derbyshire"},
            { "Matlock","Derbyshire"},
            { "Melbourne","Derbyshire"},
            { "Netherthorpe","Derbyshire"},
            { "New Mills","Derbyshire"},
            { "Over Woodhouse","Derbyshire"},
            { "Ripley","Derbyshire"},
            { "Sandiacre","Derbyshire"},
            { "Shallcross","Derbyshire"},
            { "Shirebrook","Derbyshire"},
            { "Swadlincote","Derbyshire"},
            { "Whaley Bridge","Derbyshire"},
            { "Wirksworth","Derbyshire"},
            { "Ashburton","Derbyshire"},
            { "Axminster","Derbyshire"},
            { "Bampton","Devon"},
            { "Barnstaple","Devon"},
            { "Bideford","Devon"},
            { "Bovey Tracey","Devon"},
            { "Bradninch","Devon"},
            { "Brixham","Devon"},
            { "Buckfastleigh","Devon"},
            { "Budleigh Salterton","Devon"},
            { "Chagford","Devon"},
            { "Chudleigh","Devon"},
            { "Chulmleigh","Devon"},
            { "Colyton","Devon"},
            { "Crediton","Devon"},
            { "Cullompton","Devon"},
            { "Dartmouth","Devon"},
            { "Dawlish","Devon"},
            { "Exeter","Devon"},
            { "Exmouth","Devon"},
            { "Great Torrington","Devon"},
            { "Hartland","Devon"},
            { "Hatherleigh","Devon"},
            { "Highampton","Devon"},
            { "Holsworthy","Devon"},
            { "Honiton","Devon"},
            { "Ilfracombe","Devon"},
            { "Ivybridge","Devon"},
            { "Kingsbridge","Devon"},
            { "Kingsteignton","Devon"},
            { "Lynton","Devon"},
            { "Modbury","Devon"},
            { "Moretonhampstead","Devon"},
            { "Newton Abbot","Devon"},
            { "North Tawton","Devon"},
            { "Northam","Devon"},
            { "Okehampton","Devon"},
            { "Ottery St Mary","Devon"},
            { "Paignton","Devon"},
            { "Plymouth","Devon"},
            { "Princetown","Devon"},
            { "Salcombe","Devon"},
            { "Seaton","Devon"},
            { "Sherford","Devon"},
            { "Sidmouth","Devon"},
            { "South Molton","Devon"},
            { "Tavistock","Devon"},
            { "Teignmouth","Devon"},
            { "Tiverton","Devon"},
            { "Topsham","Devon"},
            { "Torquay","Devon"},
            { "Totnes","Devon"},
            { "Beaminster","Devon"},
            { "Blandford Forum","Devon"},
            { "Bournemouth","Dorset"},
            { "Bridport","Dorset"},
            { "Chickerell","Dorset"},
            { "Christchurch","Dorset"},
            { "Dorchester","Dorset"},
            { "Ferndown","Dorset"},
            { "Gillingham","Dorset"},
            { "Highcliffe","Dorset"},
            { "Lyme Regis","Dorset"},
            { "Poole","Dorset"},
            { "Portland","Dorset"},
            { "Shaftesbury","Dorset"},
            { "Sherborne","Dorset"},
            { "Stalbridge","Dorset"},
            { "Sturminster Newton","Dorset"},
            { "Swanage","Dorset"},
            { "Verwood","Dorset"},
            { "Wareham","Dorset"},
            { "Weymouth","Dorset"},
            { "Wimborne Minster","Dorset"},
            { "Beverley","Dorset"},
            { "Bridlington","Dorset"},
            { "Brough","East Riding of Yorkshire"},
            { "Driffield","East Riding of Yorkshire"},
            { "Goole","East Riding of Yorkshire"},
            { "Hedon","East Riding of Yorkshire"},
            { "Hessle","East Riding of Yorkshire"},
            { "Hornsea","East Riding of Yorkshire"},
            { "Howden","East Riding of Yorkshire"},
            { "Market Weighton","East Riding of Yorkshire"},
            { "Pocklington","East Riding of Yorkshire"},
            { "Snaith","East Riding of Yorkshire"},
            { "South Cave","East Riding of Yorkshire"},
            { "Withernsea","East Riding of Yorkshire"},
            { "Battle","East Riding of Yorkshire"},
            { "Bexhill on Sea","East Riding of Yorkshire"},
            { "Brighton","East Sussex"},
            { "Crowborough","East Sussex"},
            { "Eastbourne","East Sussex"},
            { "Hailsham","East Sussex"},
            { "Hastings","East Sussex"},
            { "Heathfield","East Sussex"},
            { "Hove","East Sussex"},
            { "Lewes","East Sussex"},
            { "Newhaven","East Sussex"},
            { "Ore Valley","East Sussex"},
            { "Peacehaven","East Sussex"},
            { "Polegate","East Sussex"},
            { "Rye","East Sussex"},
            { "Seaford","East Sussex"},
            { "Telscombe","East Sussex"},
            { "Uckfield","East Sussex"},
            { "Wadhurst","East Sussex"},
            { "Winchelsea","East Sussex"},
            { "Basildon","East Sussex"},
            { "Billericay","East Sussex"},
            { "Braintree","Essex"},
            { "Brentwood","Essex"},
            { "Brightlingsea","Essex"},
            { "Buckhurst Hill","Essex"},
            { "Burnham on Crouch","Essex"},
            { "Canvey Island","Essex"},
            { "Chafford Hundred","Essex"},
            { "Chelmsford","Essex"},
            { "Clackwell","Essex"},
            { "Clacton on Sea","Essex"},
            { "Coggeshall","Essex"},
            { "Colchester","Essex"},
            { "Corringham","Essex"},
            { "Dovercourt","Essex"},
            { "Eastwood","Essex"},
            { "Epping","Essex"},
            { "Frinton on Sea","Essex"},
            { "Grays","Essex"},
            { "Great Dunmow","Essex"},
            { "Hadleigh","Essex"},
            { "Halstead","Essex"},
            { "Harlow","Essex"},
            { "Harwich","Essex"},
            { "Heybridge","Essex"},
            { "Hockley","Essex"},
            { "Holland on Sea","Essex"},
            { "Ingatestone","Essex"},
            { "Laindon","Essex"},
            { "Langdon Hills","Essex"},
            { "Leigh on Sea","Essex"},
            { "Loughton","Essex"},
            { "Maldon","Essex"},
            { "Manningtree","Essex"},
            { "North Shoebury","Essex"},
            { "Ongar","Essex"},
            { "Parkeston","Essex"},
            { "Pitsea","Essex"},
            { "Prettlewell","Essex"},
            { "Rayleigh","Essex"},
            { "Rochford","Essex"},
            { "Romford","Essex"},
            { "Saffron Walden","Essex"},
            { "Shoeburyness","Essex"},
            { "South Benfleet","Essex"},
            { "South Woodham Ferrers","Essex"},
            { "Southchurch","Essex"},
            { "Southend on Sea","Essex"},
            { "Southminster","Essex"},
            { "Stanfield le Hope","Essex"},
            { "Thaxted","Essex"},
            { "Thorpe Bay","Essex"},
            { "Tilbury","Essex"},
            { "Waltham Abbey","Essex"},
            { "Walton on the Naze","Essex"},
            { "West Mersea","Essex"},
            { "West Thurrock","Essex"},
            { "West Tilbury","Essex"},
            { "Westcliff on Sea","Essex"},
            { "Wickford","Essex"},
            { "Witham","Essex"},
            { "Wivenhoe","Essex"},
            { "Berkeley","Essex"},
            { "Bradley Stoke","Essex"},
            { "Cheltenham","Gloucestershire"},
            { "Chipping Campden","Gloucestershire"},
            { "Chipping Sodbury","Gloucestershire"},
            { "Cinderford","Gloucestershire"},
            { "Cirencester","Gloucestershire"},
            { "Coleford","Gloucestershire"},
            { "Dursley","Gloucestershire"},
            { "Fairford","Gloucestershire"},
            { "Filton","Gloucestershire"},
            { "Gloucester","Gloucestershire"},
            { "Kingswood","Gloucestershire"},
            { "Lechlade","Gloucestershire"},
            { "Lydney","Gloucestershire"},
            { "Minchinhampton","Gloucestershire"},
            { "Mitcheldean","Gloucestershire"},
            { "Moreton in Marsh","Gloucestershire"},
            { "Nailsworth","Gloucestershire"},
            { "Newent","Gloucestershire"},
            { "Northleach","Gloucestershire"},
            { "Painswick","Gloucestershire"},
            { "Patchway","Gloucestershire"},
            { "Stonehouse","Gloucestershire"},
            { "Stow on the Wold","Gloucestershire"},
            { "Stroud","Gloucestershire"},
            { "Tetbury","Gloucestershire"},
            { "Tewkesbury","Gloucestershire"},
            { "Thornbury","Gloucestershire"},
            { "Wickwar","Gloucestershire"},
            { "Winchcombe","Gloucestershire"},
            { "Wotton under Edge","Gloucestershire"},
            { "Yate","Gloucestershire"},
            { "Acton","Gloucestershire"},
            { "Barking","Gloucestershire"},
            { "Barnes","Greater London"},
            { "Beckenham","Greater London"},
            { "Bexley","Greater London"},
            { "Brentford","Greater London"},
            { "Bromley","Greater London"},
            { "Chingford","Greater London"},
            { "Croydon","Greater London"},
            { "Dagenham","Greater London"},
            { "Ealing","Greater London"},
            { "East Ham","Greater London"},
            { "Edgware","Greater London"},
            { "Edmonton","Greater London"},
            { "Enfield","Greater London"},
            { "Erith","Greater London"},
            { "Finchley","Greater London"},
            { "Harrow","Greater London"},
            { "Hendon","Greater London"},
            { "Hornsey","Greater London"},
            { "Ilford","Greater London"},
            { "Kingston upon Thames","Greater London"},
            { "Leyton","Greater London"},
            { "Mitcham","Greater London"},
            { "Richmond","Greater London"},
            { "Southall","Greater London"},
            { "Southgate","Greater London"},
            { "St Mary Cray","Greater London"},
            { "Surbiton","Greater London"},
            { "Tottenham","Greater London"},
            { "Twickenham","Greater London"},
            { "Uxbridge","Greater London"},
            { "Walthamstow","Greater London"},
            { "Wembley","Greater London"},
            { "West Ham","Greater London"},
            { "Willesden","Greater London"},
            { "Wimbledon","Greater London"},
            { "Wood Green","Greater London"},
            { "Altrincham","Greater London"},
            { "Ashton in Makerfield","Greater London"},
            { "Ashton under Lyne","Greater Manchester"},
            { "Atherton","Greater Manchester"},
            { "Audenshaw","Greater Manchester"},
            { "Blackrod","Greater Manchester"},
            { "Bolton","Greater Manchester"},
            { "Bury","Greater Manchester"},
            { "Cadishead","Greater Manchester"},
            { "Chadderton","Greater Manchester"},
            { "Cheadle","Greater Manchester"},
            { "Cheadle Hulme","Greater Manchester"},
            { "Denton","Greater Manchester"},
            { "Droylsden","Greater Manchester"},
            { "Dukinfield","Greater Manchester"},
            { "Eccles","Greater Manchester"},
            { "Failsworth","Greater Manchester"},
            { "Farnworth","Greater Manchester"},
            { "Golbourne","Greater Manchester"},
            { "Heywood","Greater Manchester"},
            { "Hindley","Greater Manchester"},
            { "Horwich","Greater Manchester"},
            { "Hyde","Greater Manchester"},
            { "Ince in Makerfield","Greater Manchester"},
            { "Irlam","Greater Manchester"},
            { "Kearsley","Greater Manchester"},
            { "Leigh","Greater Manchester"},
            { "Littleborough","Greater Manchester"},
            { "Manchester","Greater Manchester"},
            { "Middleton","Greater Manchester"},
            { "Milnrow","Greater Manchester"},
            { "Mossley","Greater Manchester"},
            { "Oldham","Greater Manchester"},
            { "Partington","Greater Manchester"},
            { "Pendlebury","Greater Manchester"},
            { "Prestwich","Greater Manchester"},
            { "Radcliffe","Greater Manchester"},
            { "Ramsbottom","Greater Manchester"},
            { "Rochdale","Greater Manchester"},
            { "Royton","Greater Manchester"},
            { "Sale","Greater Manchester"},
            { "Salford","Greater Manchester"},
            { "Shaw and Crompton","Greater Manchester"},
            { "Stalybridge","Greater Manchester"},
            { "Stockport","Greater Manchester"},
            { "Stretford","Greater Manchester"},
            { "Swinton","Greater Manchester"},
            { "Tottington","Greater Manchester"},
            { "Tyldsley","Greater Manchester"},
            { "Walkden","Greater Manchester"},
            { "Westhoughton","Greater Manchester"},
            { "Whitefield","Greater Manchester"},
            { "Wigan","Greater Manchester"},
            { "Worsley","Greater Manchester"},
            { "Aldershot","Greater Manchester"},
            { "Alton","Greater Manchester"},
            { "Andover","Hampshire"},
            { "Basingstoke","Hampshire"},
            { "Bishop's Waltham","Hampshire"},
            { "Blackwater and Hawley","Hampshire"},
            { "Bordon","Hampshire"},
            { "Eastleigh","Hampshire"},
            { "Emsworth","Hampshire"},
            { "Fareham","Hampshire"},
            { "Farnborough","Hampshire"},
            { "Fleet","Hampshire"},
            { "Fordingbridge","Hampshire"},
            { "Gosport","Hampshire"},
            { "Havant","Hampshire"},
            { "Hedge End","Hampshire"},
            { "Hythe","Hampshire"},
            { "Lee on the Solent","Hampshire"},
            { "Lymington","Hampshire"},
            { "Lyndhurst","Hampshire"},
            { "New Alresford","Hampshire"},
            { "New Milton","Hampshire"},
            { "North Camp","Hampshire"},
            { "Petersfield","Hampshire"},
            { "Portchester","Hampshire"},
            { "Portsmouth","Hampshire"},
            { "Ringwood","Hampshire"},
            { "Romsey","Hampshire"},
            { "Southampton","Hampshire"},
            { "Southsea","Hampshire"},
            { "Southwick","Hampshire"},
            { "Tadley","Hampshire"},
            { "Totton","Hampshire"},
            { "Waterlooville","Hampshire"},
            { "Whitchurch","Hampshire"},
            { "Whitehill","Hampshire"},
            { "Wickham","Hampshire"},
            { "Winchester","Hampshire"},
            { "Yateley","Hampshire"},
            { "Bromyard","Hampshire"},
            { "Hatfield","Hampshire"},
            { "Hereford","Herefordshire"},
            { "Kington","Herefordshire"},
            { "Ledbury","Herefordshire"},
            { "Leominster","Herefordshire"},
            { "Ross on Wye","Herefordshire"},
            { "Baldock","Herefordshire"},
            { "Barnet","Herefordshire"},
            { "Berkhamsted","Herefordshire"},
            { "Bishop's Stortford","Hertfordshire"},
            { "Borehamwood","Hertfordshire"},
            { "Broxbourne","Hertfordshire"},
            { "Buntingford","Hertfordshire"},
            { "Bushey","Hertfordshire"},
            { "Cheshunt","Hertfordshire"},
            { "Chorleywood","Hertfordshire"},
            { "Elstree","Hertfordshire"},
            { "Harpenden","Hertfordshire"},
            { "Hemel Hempstead","Hertfordshire"},
            { "Hertford","Hertfordshire"},
            { "Hitchin","Hertfordshire"},
            { "Hoddesdon","Hertfordshire"},
            { "Letchworth","Hertfordshire"},
            { "Potters Bar","Hertfordshire"},
            { "Rickmansworth","Hertfordshire"},
            { "Royston","Hertfordshire"},
            { "Sawbridgeworth","Hertfordshire"},
            { "Stevenage","Hertfordshire"},
            { "Tring","Hertfordshire"},
            { "Waltham Cross","Hertfordshire"},
            { "Ware","Hertfordshire"},
            { "Watford","Hertfordshire"},
            { "Welwyn Garden City","Hertfordshire"},
            { "Appley","Hertfordshire"},
            { "Brading","Hertfordshire"},
            { "Cowes","Hertfordshire"},
            { "East Cowes","Hertfordshire"},
            { "Newport","Isle of Wight"},
            { "Ryde","Isle of Wight"},
            { "Sandown","Isle of Wight"},
            { "Shanklin","Isle of Wight"},
            { "Ventnor","Isle of Wight"},
            { "Yarmouth","Isle of Wight"},
            { "Ashford","Isle of Wight"},
            { "Broadstairs","Isle of Wight"},
            { "Canterbury","Isle of Wight"},
            { "Chatham","Isle of Wight"},
            { "Cranbrook","Kent"},
            { "Crayford","Kent"},
            { "Dartford","Kent"},
            { "Deal","Kent"},
            { "Dover","Kent"},
            { "Edenbridge","Kent"},
            { "Faversham","Kent"},
            { "Folkestone","Kent"},
            { "Fordwich","Kent"},
            { "Gravesend","Kent"},
            { "Greenhill","Kent"},
            { "Herne Bay","Kent"},
            { "Lydd","Kent"},
            { "Maidstone","Kent"},
            { "Margate","Kent"},
            { "Minster","Kent"},
            { "New Romney","Kent"},
            { "Northfleet","Kent"},
            { "Orpington","Kent"},
            { "Paddock Wood","Kent"},
            { "Queenborough","Kent"},
            { "Rainham","Kent"},
            { "Ramsgate","Kent"},
            { "Rochester","Kent"},
            { "Royal Tunbridge Wells","Kent"},
            { "Sandwich","Kent"},
            { "Sevenoaks","Kent"},
            { "Sheerness","Kent"},
            { "Sittingbourne","Kent"},
            { "Snodland","Kent"},
            { "Southborough","Kent"},
            { "Strood","Kent"},
            { "Swanley","Kent"},
            { "Swanscombe and Greenhithe","Kent"},
            { "Tenterden","Kent"},
            { "Tonbridge","Kent"},
            { "Tunbridge Wells","Kent"},
            { "West Malling","Kent"},
            { "Westerham","Kent"},
            { "Westgate on Sea","Kent"},
            { "Whitstable","Kent"},
            { "Accrington","Kent"},
            { "Adlington","Kent"},
            { "Bacup","Kent"},
            { "Barnoldswick","Kent"},
            { "Blackburn","Kent"},
            { "Blackpool","Kent"},
            { "Brierfield","Lancashire"},
            { "Burnley","Lancashire"},
            { "Carnforth","Lancashire"},
            { "Chorley","Lancashire"},
            { "Clayton le Moors","Lancashire"},
            { "Cleveleys","Lancashire"},
            { "Clitheroe","Lancashire"},
            { "Colne","Lancashire"},
            { "Darwen","Lancashire"},
            { "Fleetwood","Lancashire"},
            { "Garstang","Lancashire"},
            { "Great Harwood","Lancashire"},
            { "Haslingden","Lancashire"},
            { "Kirkham","Lancashire"},
            { "Lancaster","Lancashire"},
            { "Leyland","Lancashire"},
            { "Longridge","Lancashire"},
            { "Lytham St Annes","Lancashire"},
            { "Medlar with Wesham","Lancashire"},
            { "Morecambe","Lancashire"},
            { "Nelson","Lancashire"},
            { "Ormskirk","Lancashire"},
            { "Oswaldtwistle","Lancashire"},
            { "Padiham","Lancashire"},
            { "Penwortham","Lancashire"},
            { "Poulton le Fylde","Lancashire"},
            { "Preesall","Lancashire"},
            { "Preston","Lancashire"},
            { "Rawtenstall","Lancashire"},
            { "Skelmersdale","Lancashire"},
            { "Thornton","Lancashire"},
            { "Thornton Cleveleys","Lancashire"},
            { "Wesham","Lancashire"},
            { "Whitworth","Lancashire"},
            { "Ashby de la Zouch","Lancashire"},
            { "Ashby Woulds","Lancashire"},
            { "Braunstone Town","Lancashire"},
            { "Coalville","Lancashire"},
            { "Earl Shilton","Lancashire"},
            { "Hinckley","Lancashire"},
            { "Leicester","Lancashire"},
            { "Loughborough","Leicestershire"},
            { "Lutterworth","Leicestershire"},
            { "Market Bosworth","Leicestershire"},
            { "Market Harborough","Leicestershire"},
            { "Melton Mowbray","Leicestershire"},
            { "Oadby","Leicestershire"},
            { "Shepshed","Leicestershire"},
            { "Syston","Leicestershire"},
            { "Wigston Magna","Leicestershire"},
            { "Alford","Leicestershire"},
            { "Barton upon Humber","Leicestershire"},
            { "Boston","Leicestershire"},
            { "Bottesford","Leicestershire"},
            { "Bourne","Leicestershire"},
            { "Brigg","Leicestershire"},
            { "Broughton","Leicestershire"},
            { "Burgh le Marsh","Lincolnshire"},
            { "Caistor","Lincolnshire"},
            { "Cleethorpes","Lincolnshire"},
            { "Coningsby","Lincolnshire"},
            { "Crowland","Lincolnshire"},
            { "Crowle","Lincolnshire"},
            { "Epworth","Lincolnshire"},
            { "Gainsborough","Lincolnshire"},
            { "Grantham","Lincolnshire"},
            { "Grimsby","Lincolnshire"},
            { "Holbeach","Lincolnshire"},
            { "Horncastle","Lincolnshire"},
            { "Immingham","Lincolnshire"},
            { "Kirton in Lindsey","Lincolnshire"},
            { "Lincoln","Lincolnshire"},
            { "Little Coates","Lincolnshire"},
            { "Long Sutton","Lincolnshire"},
            { "Louth","Lincolnshire"},
            { "Mablethorpe","Lincolnshire"},
            { "Mablethorpe and Sutton","Lincolnshire"},
            { "Market Deeping","Lincolnshire"},
            { "Market Rasen","Lincolnshire"},
            { "North Hykeham","Lincolnshire"},
            { "Scunthorpe","Lincolnshire"},
            { "Skegness","Lincolnshire"},
            { "Sleaford","Lincolnshire"},
            { "Spalding","Lincolnshire"},
            { "Spilsby","Lincolnshire"},
            { "Stamford","Lincolnshire"},
            { "The Deepings","Lincolnshire"},
            { "Wainfleet","Lincolnshire"},
            { "Winterton","Lincolnshire"},
            { "Wragby","Lincolnshire"},
            { "Bebington","Lincolnshire"},
            { "Birkenhead","Lincolnshire"},
            { "Bootle","Lincolnshire"},
            { "Bromborough","Lincolnshire"},
            { "Crosby","Lincolnshire"},
            { "Earlestown","Lincolnshire"},
            { "Formby","Lincolnshire"},
            { "Halewood","Merseyside"},
            { "Heswall","Merseyside"},
            { "Hoylake","Merseyside"},
            { "Huyton","Merseyside"},
            { "Kirkby","Merseyside"},
            { "Liverpool","Merseyside"},
            { "Maghull","Merseyside"},
            { "Newton le Willows","Merseyside"},
            { "Prescot","Merseyside"},
            { "Rainford","Merseyside"},
            { "Rainhill","Merseyside"},
            { "Southport","Merseyside"},
            { "St Helens","Merseyside"},
            { "Wallasey","Merseyside"},
            { "Whiston","Merseyside"},
            { "Acle","Merseyside"},
            { "Attleborough","Merseyside"},
            { "Aylsham","Merseyside"},
            { "Caister on Sea","Merseyside"},
            { "Cromer","Merseyside"},
            { "Dereham","Merseyside"},
            { "Diss","Merseyside"},
            { "Downham Market","Norfolk"},
            { "Fakenham","Norfolk"},
            { "Gorleston","Norfolk"},
            { "Great Yarmouth","Norfolk"},
            { "Hingham","Norfolk"},
            { "Holt","Norfolk"},
            { "Hunstanton","Norfolk"},
            { "King's Lynn","Norfolk"},
            { "Loddon","Norfolk"},
            { "North Walsham","Norfolk"},
            { "Norwich","Norfolk"},
            { "Rackheath","Norfolk"},
            { "Redenhall with Harleston","Norfolk"},
            { "Reepham","Norfolk"},
            { "Sheringham","Norfolk"},
            { "Stalham","Norfolk"},
            { "Swaffham","Norfolk"},
            { "Thetford","Norfolk"},
            { "Thorpe St Andrew","Norfolk"},
            { "Watton","Norfolk"},
            { "Wells next the Sea","Norfolk"},
            { "Wroxham","Norfolk"},
            { "Wymondham","Norfolk"},
            { "Bedale","Norfolk"},
            { "Bentham","Norfolk"},
            { "Boroughbridge","Norfolk"},
            { "Colburn","Norfolk"},
            { "Easingwold","Norfolk"},
            { "Eston","Norfolk"},
            { "Filey","Norfolk"},
            { "Grangetown","North Yorkshire"},
            { "Grassington","North Yorkshire"},
            { "Guisborough","North Yorkshire"},
            { "Harrogate","North Yorkshire"},
            { "Hawes","North Yorkshire"},
            { "Haxby","North Yorkshire"},
            { "Helmsley","North Yorkshire"},
            { "Ingleby Barwick","North Yorkshire"},
            { "Kirkbymoorside","North Yorkshire"},
            { "Knaresborough","North Yorkshire"},
            { "Leyburn","North Yorkshire"},
            { "Loftus","North Yorkshire"},
            { "Malton","North Yorkshire"},
            { "Masham","North Yorkshire"},
            { "Middleham","North Yorkshire"},
            { "Middlesbrough","North Yorkshire"},
            { "Northallerton","North Yorkshire"},
            { "Norton on Derwent","North Yorkshire"},
            { "Pateley Bridge","North Yorkshire"},
            { "Pickering","North Yorkshire"},
            { "Redcar","North Yorkshire"},
            { "Ripon","North Yorkshire"},
            { "Robin Hood's Bay","North Yorkshire"},
            { "Saltburn by the Sea","North Yorkshire"},
            { "Scarborough","North Yorkshire"},
            { "Selby","North Yorkshire"},
            { "Settle","North Yorkshire"},
            { "Sherburn in Elmet","North Yorkshire"},
            { "Skelton in Cleveland","North Yorkshire"},
            { "Skipton","North Yorkshire"},
            { "Stokesley","North Yorkshire"},
            { "Tadcaster","North Yorkshire"},
            { "Thirsk","North Yorkshire"},
            { "Thornaby on Tees","North Yorkshire"},
            { "Whitby","North Yorkshire"},
            { "Yarm","North Yorkshire"},
            { "York","North Yorkshire"},
            { "Brackley","North Yorkshire"},
            { "Burton Latimer","North Yorkshire"},
            { "Corby","North Yorkshire"},
            { "Daventry","North Yorkshire"},
            { "Desborough","North Yorkshire"},
            { "Higham Ferrers","North Yorkshire"},
            { "Irthlingborough","North Yorkshire"},
            { "Kettering","North Yorkshire"},
            { "Northampton","North Yorkshire"},
            { "Oundle","Northamptonshire"},
            { "Raunds","Northamptonshire"},
            { "Rothwell","Northamptonshire"},
            { "Rushden","Northamptonshire"},
            { "Thrapston","Northamptonshire"},
            { "Towcester","Northamptonshire"},
            { "Wellingborough","Northamptonshire"},
            { "Alnwick","Northamptonshire"},
            { "Amble","Northamptonshire"},
            { "Ashington","Northamptonshire"},
            { "Bedlington","Northamptonshire"},
            { "Berwick upon Tweed","Northamptonshire"},
            { "Blyth","Northamptonshire"},
            { "Corbridge","Northamptonshire"},
            { "Cramlington","Northamptonshire"},
            { "Haltwhistle","Northamptonshire"},
            { "Hexham","Northumberland"},
            { "Morpeth","Northumberland"},
            { "Newbiggin by the Sea","Northumberland"},
            { "Ponteland","Northumberland"},
            { "Prudhoe","Northumberland"},
            { "Rothbury","Northumberland"},
            { "West Bedlington","Northumberland"},
            { "Wooler","Northumberland"},
            { "Arnold","Northumberland"},
            { "Beeston","Northumberland"},
            { "Bingham","Northumberland"},
            { "Bracebridge","Northumberland"},
            { "Bulwell","Northumberland"},
            { "Carlton","Northumberland"},
            { "Cotgrave","Northumberland"},
            { "East Retford","Northumberland"},
            { "Harworth and Bircotes","Northumberland"},
            { "Hucknall","Nottinghamshire"},
            { "Kilton","Nottinghamshire"},
            { "Kimberley","Nottinghamshire"},
            { "Kirkby in Ashfield","Nottinghamshire"},
            { "Mansfield","Nottinghamshire"},
            { "Netherfield","Nottinghamshire"},
            { "Newark on Trent","Nottinghamshire"},
            { "Nottingham","Nottinghamshire"},
            { "Ollerton","Nottinghamshire"},
            { "Ollerton and Boughton","Nottinghamshire"},
            { "Retford","Nottinghamshire"},
            { "Southwell","Nottinghamshire"},
            { "Stapleford","Nottinghamshire"},
            { "Sutton in Ashfield","Nottinghamshire"},
            { "Warsop","Nottinghamshire"},
            { "West Bridgefield","Nottinghamshire"},
            { "Worksop","Nottinghamshire"},
            { "Abingdon","Nottinghamshire"},
            { "Banbury","Nottinghamshire"},
            { "Bicester","Nottinghamshire"},
            { "Burford","Nottinghamshire"},
            { "Carterton","Nottinghamshire"},
            { "Charlbury","Nottinghamshire"},
            { "Chipping Norton","Nottinghamshire"},
            { "Didcot","Nottinghamshire"},
            { "Faringdon","Nottinghamshire"},
            { "Henley on Thames","Nottinghamshire"},
            { "Neithrop","Oxfordshire"},
            { "Oxford","Oxfordshire"},
            { "Ruscote","Oxfordshire"},
            { "Thame","Oxfordshire"},
            { "Wallingford","Oxfordshire"},
            { "Wantage","Oxfordshire"},
            { "Watlington","Oxfordshire"},
            { "Weston Otmoor","Oxfordshire"},
            { "Witney","Oxfordshire"},
            { "Woodstock","Oxfordshire"},
            { "Oakham","Oxfordshire"},
            { "Uppingham","Oxfordshire"},
            { "Bishop's Castle","Oxfordshire"},
            { "Bridgnorth","Oxfordshire"},
            { "Broseley","Oxfordshire"},
            { "Church Stretton","Oxfordshire"},
            { "Cleobury Mortimer","Oxfordshire"},
            { "Clun","Oxfordshire"},
            { "Craven Arms","Oxfordshire"},
            { "Dawley","Oxfordshire"},
            { "Ellesmere","Oxfordshire"},
            { "Ludlow","Rutland"},
            { "Madeley","Rutland"},
            { "Market Drayton","Shropshire"},
            { "Much Wenlock","Shropshire"},
            { "Oakengates","Shropshire"},
            { "Oswestry","Shropshire"},
            { "Shifnal","Shropshire"},
            { "Shrewsbury","Shropshire"},
            { "Telford","Shropshire"},
            { "Wellington","Shropshire"},
            { "Wem","Shropshire"},
            { "Axbridge","Shropshire"},
            { "Bath","Shropshire"},
            { "Bridgwater","Shropshire"},
            { "Bruton","Shropshire"},
            { "Burnham on Sea","Shropshire"},
            { "Castle Cary","Shropshire"},
            { "Chard","Shropshire"},
            { "Clevedon","Shropshire"},
            { "Crewkerne","Shropshire"},
            { "Dulverton","Shropshire"},
            { "Frome","Shropshire"},
            { "Glastonbury","Shropshire"},
            { "Highbridge","Shropshire"},
            { "Ilminster","Somerset"},
            { "Keynsham","Somerset"},
            { "Langport","Somerset"},
            { "Midsomer Norton","Somerset"},
            { "Minehead","Somerset"},
            { "Nailsea","Somerset"},
            { "North Petherton","Somerset"},
            { "Norton Radstock","Somerset"},
            { "Portishead","Somerset"},
            { "Portishead and North Weston","Somerset"},
            { "Radstock","Somerset"},
            { "Shepton Mallet","Somerset"},
            { "Somerton","Somerset"},
            { "South Petherton","Somerset"},
            { "Street","Somerset"},
            { "Taunton","Somerset"},
            { "Watchet","Somerset"},
            { "Wells","Somerset"},
            { "Weston super Mare","Somerset"},
            { "Wincanton","Somerset"},
            { "Wiveliscombe","Somerset"},
            { "Yeovil","Somerset"},
            { "Anston","Somerset"},
            { "Askern","Somerset"},
            { "Barnsley","Somerset"},
            { "Bawtry","Somerset"},
            { "Brierley","Somerset"},
            { "Conisbrough","Somerset"},
            { "Dinnington","Somerset"},
            { "Doncaster","Somerset"},
            { "Edlington","Somerset"},
            { "Hoyland","Somerset"},
            { "Maltby","Somerset"},
            { "Mexborough","Somerset"},
            { "Penistone","Somerset"},
            { "Rotherham","Somerset"},
            { "Sheffield","Somerset"},
            { "Stainforth","South Yorkshire"},
            { "Stocksbridge","South Yorkshire"},
            { "Thorne","South Yorkshire"},
            { "Tickhill","South Yorkshire"},
            { "Wath upon Dearne","South Yorkshire"},
            { "Wombwell","South Yorkshire"},
            { "Biddulph","South Yorkshire"},
            { "Burntwood","South Yorkshire"},
            { "Burslem","South Yorkshire"},
            { "Burton upon Trent","South Yorkshire"},
            { "Cannock","South Yorkshire"},
            { "Eccleshall","South Yorkshire"},
            { "Fazeley","South Yorkshire"},
            { "Fenton","South Yorkshire"},
            { "Hednesford","South Yorkshire"},
            { "Kidsgrove","South Yorkshire"},
            { "Leek","South Yorkshire"},
            { "Lichfield","South Yorkshire"},
            { "Longton","South Yorkshire"},
            { "Newcastle under Lyme","South Yorkshire"},
            { "Penkridge","South Yorkshire"},
            { "Perry Crofts","South Yorkshire"},
            { "Rugeley","South Yorkshire"},
            { "Stafford","Staffordshire"},
            { "Stoke on Trent","Staffordshire"},
            { "Stone","Staffordshire"},
            { "Tamworth","Staffordshire"},
            { "Tunstall","Staffordshire"},
            { "Uttoxeter","Staffordshire"},
            { "Aldeburgh","Staffordshire"},
            { "Beccles","Staffordshire"},
            { "Brandon","Staffordshire"},
            { "Bungay","Staffordshire"},
            { "Bury St Edmunds","Staffordshire"},
            { "Carlton Colville","Staffordshire"},
            { "Clare","Staffordshire"},
            { "Dommoc","Staffordshire"},
            { "Dunwich","Staffordshire"},
            { "Eye","Staffordshire"},
            { "Felixstowe","Staffordshire"},
            { "Framlingham","Staffordshire"},
            { "Halesworth","Staffordshire"},
            { "Haverhill","Staffordshire"},
            { "Ipswich","Staffordshire"},
            { "Kesgrave","Staffordshire"},
            { "Leiston","Staffordshire"},
            { "Lowestoft","Staffordshire"},
            { "Mildenhall","Staffordshire"},
            { "Needham Market","Suffolk"},
            { "Newmarket","Suffolk"},
            { "Orford","Suffolk"},
            { "Otley","Suffolk"},
            { "Saxmundham","Suffolk"},
            { "Southwold","Suffolk"},
            { "Stowmarket","Suffolk"},
            { "Sudbury","Suffolk"},
            { "Woodbridge","Suffolk"},
            { "Beltchingley","Suffolk"},
            { "Camberley","Suffolk"},
            { "Chertsey","Suffolk"},
            { "Dorking","Suffolk"},
            { "Egham","Suffolk"},
            { "Epsom","Suffolk"},
            { "Esher","Suffolk"},
            { "Farnham","Suffolk"},
            { "Godalming","Suffolk"},
            { "Gomshall","Suffolk"},
            { "Gratton","Suffolk"},
            { "Great Brookham","Suffolk"},
            { "Guildford","Suffolk"},
            { "Haslemere","Suffolk"},
            { "Horley","Suffolk"},
            { "Leatherhead","Suffolk"},
            { "Redhill","Suffolk"},
            { "Reigate","Suffolk"},
            { "Southwark","Suffolk"},
            { "Staines upon Thames","Suffolk"},
            { "Walton on Thames","Surrey"},
            { "Weybridge","Surrey"},
            { "Woking","Surrey"},
            { "Birtley","Surrey"},
            { "Blaydon on tyne","Surrey"},
            { "Cullercoats","Surrey"},
            { "Darsley Park","Surrey"},
            { "Dunston","Surrey"},
            { "Gateshead","Surrey"},
            { "Hetton","Surrey"},
            { "Houghton le Spring","Surrey"},
            { "Howdon","Surrey"},
            { "Jarrow","Surrey"},
            { "Killingworth","Surrey"},
            { "Little Benton","Surrey"},
            { "Longbenton","Surrey"},
            { "Low Fell","Surrey"},
            { "Newcastle upon Tyne","Surrey"},
            { "North Shields","Surrey"},
            { "Ryton","Surrey"},
            { "Sheriff Hill","Surrey"},
            { "South Shields","Surrey"},
            { "Sunderland","Surrey"},
            { "Tynemouth","Surrey"},
            { "Wallsend","Surrey"},
            { "Washington","Surrey"},
            { "Whitley Bay","Tyne and Wear"},
            { "Willington Quay","Tyne and Wear"},
            { "Windy Nook","Tyne and Wear"},
            { "Alcester","Tyne and Wear"},
            { "Atherstone","Tyne and Wear"},
            { "Bedworth","Tyne and Wear"},
            { "Coleshill","Tyne and Wear"},
            { "Henley in Arden","Tyne and Wear"},
            { "Kenilworth","Tyne and Wear"},
            { "Middle Quinton","Tyne and Wear"},
            { "Nuneaton","Tyne and Wear"},
            { "Royal Leamington Spa","Tyne and Wear"},
            { "Rugby","Tyne and Wear"},
            { "Shipston on Stour","Tyne and Wear"},
            { "Southam","Tyne and Wear"},
            { "Stratford upon Avon","Tyne and Wear"},
            { "Warwick","Tyne and Wear"},
            { "Whitnash","Tyne and Wear"},
            { "Aldridge","Tyne and Wear"},
            { "Bilston","Tyne and Wear"},
            { "Birmingham","Tyne and Wear"},
            { "Blackheath","Tyne and Wear"},
            { "Bloxwich","Tyne and Wear"},
            { "Brierley Hill","Tyne and Wear"},
            { "Brownhills","Tyne and Wear"},
            { "Coal Pool","Tyne and Wear"},
            { "Coseley","Warwickshire"},
            { "Coventry","Warwickshire"},
            { "Cradley Heath","Warwickshire"},
            { "Darlaston","Warwickshire"},
            { "Dudley","Warwickshire"},
            { "Fordbridge","Warwickshire"},
            { "Gornal","Warwickshire"},
            { "Halesowen","Warwickshire"},
            { "Lye","Warwickshire"},
            { "Moxley","Warwickshire"},
            { "Netherton","Warwickshire"},
            { "Oldbury","Warwickshire"},
            { "Pelsall","Warwickshire"},
            { "Rowley Regis","Warwickshire"},
            { "Sedgley","Warwickshire"},
            { "Smethwick","West Midlands"},
            { "Solihull","West Midlands"},
            { "Stourbridge","West Midlands"},
            { "Sutton Coldfield","West Midlands"},
            { "Tipton","West Midlands"},
            { "Walsall","West Midlands"},
            { "Wednesbury","West Midlands"},
            { "Wednesfield","West Midlands"},
            { "West Bromwich","West Midlands"},
            { "Willenhall","West Midlands"},
            { "Wolverhampton","West Midlands"},
            { "Arundel","West Midlands"},
            { "Bognor Regis","West Midlands"},
            { "Burgess Hill","West Midlands"},
            { "Chichester","West Midlands"},
            { "Crawley","West Midlands"},
            { "Cuckfield","West Midlands"},
            { "East Grinstead","West Midlands"},
            { "Haywards Heath","West Midlands"},
            { "Horsham","West Midlands"},
            { "Littlehampton","West Midlands"},
            { "Midhurst","West Midlands"},
            { "Petworth","West Midlands"},
            { "Selsey","West Midlands"},
            { "Shoreham by Sea","West Midlands"},
            { "Steyning","West Midlands"},
            { "Worthing","West Midlands"},
            { "Baildon","West Midlands"},
            { "Batley","West Midlands"},
            { "Bingley","West Midlands"},
            { "Bradford","West Midlands"},
            { "Brighouse","West Midlands"},
            { "Castleford","West Midlands"},
            { "Cleckheaton","West Midlands"},
            { "Denholme","West Sussex"},
            { "Dewsbury","West Sussex"},
            { "Elland","West Sussex"},
            { "Farsley","West Sussex"},
            { "Featherstone","West Sussex"},
            { "Garforth","West Sussex"},
            { "Guiseley","West Sussex"},
            { "Halifax","West Sussex"},
            { "Hebden Bridge","West Sussex"},
            { "Hebden Royd","West Sussex"},
            { "Heckmondwike","West Sussex"},
            { "Hemsworth","West Sussex"},
            { "Holmfirth","West Sussex"},
            { "Horsforth","West Sussex"},
            { "Huddersfield","West Sussex"},
            { "Ilkley","West Sussex"},
            { "Keighley","West Sussex"},
            { "Knottingley","West Yorkshire"},
            { "Leeds","West Yorkshire"},
            { "Meltham","West Yorkshire"},
            { "Mirfield","West Yorkshire"},
            { "Morley","West Yorkshire"},
            { "Mytholmroyd","West Yorkshire"},
            { "Normanton","West Yorkshire"},
            { "Ossett","West Yorkshire"},
            { "Pontefract","West Yorkshire"},
            { "Pudsey","West Yorkshire"},
            { "Shipley","West Yorkshire"},
            { "Silsden","West Yorkshire"},
            { "South Elmsall","West Yorkshire"},
            { "South Kirkby and Moorthorpe","West Yorkshire"},
            { "Sowerby Bridge","West Yorkshire"},
            { "Todmorden","West Yorkshire"},
            { "Wakefield","West Yorkshire"},
            { "Wetherby","West Yorkshire"},
            { "Yeadon","West Yorkshire"},
            { "Amesbury","West Yorkshire"},
            { "Bradford on Avon","West Yorkshire"},
            { "Calne","West Yorkshire"},
            { "Chippenham","West Yorkshire"},
            { "Corsham","West Yorkshire"},
            { "Cricklade","West Yorkshire"},
            { "Devizes","West Yorkshire"},
            { "Highworth","West Yorkshire"},
            { "Ludgershall","West Yorkshire"},
            { "Malmesbury","West Yorkshire"},
            { "Marlborough","West Yorkshire"},
            { "Melksham","West Yorkshire"},
            { "Mere","West Yorkshire"},
            { "Royal Wootton Bassett","West Yorkshire"},
            { "Salisbury","West Yorkshire"},
            { "Swindon","West Yorkshire"},
            { "Tidworth","West Yorkshire"},
            { "Tisbury","West Yorkshire"},
            { "Trowbridge","West Yorkshire"},
            { "Warminster","West Yorkshire"},
            { "Westbury","West Yorkshire"},
            { "Wilton","West Yorkshire"},
            { "Bewdley","West Yorkshire"},
            { "Bromsgrove","West Yorkshire"},
            { "Droitwich Spa","West Yorkshire"},
            { "Evesham","West Yorkshire"},
            { "Great Malvern","Wiltshire"},
            { "Kidderminster","Wiltshire"},
            { "Malvern","Wiltshire"},
            { "Pershore","Wiltshire"},
            { "Redditch","Wiltshire"},
            { "Stourport on Severn","Wiltshire"},
            { "Tenbury Wells","Wiltshire"},
            { "Upton upon Severn","Wiltshire"},
            { "Worcester","Wiltshire"},
            { "Antrim","Wiltshire"},
            { "Ballycastle","Wiltshire"},
            { "Ballyclare","Wiltshire"},
            { "Ballymena","Wiltshire"},
            { "Ballymoney","Wiltshire"},
            { "Bushmills","Wiltshire"},
            { "Carrickfergus","Wiltshire"},
            { "Crumlin","Wiltshire"},
            { "Greenisland","Wiltshire"},
            { "Larne","Wiltshire"},
            { "Lisburn","Wiltshire"},
            { "Merville Garden Village","Wiltshire"},
            { "Newtownabbey","Wiltshire"},
            { "Portrush","Worcestershire"},
            { "Randalstown","Worcestershire"},
            { "Armagh","Worcestershire"},
            { "Craigavon","Worcestershire"},
            { "Lurgan","Worcestershire"},
            { "Markethill","Worcestershire"},
            { "Newry","Worcestershire"},
            { "Portadown","Worcestershire"},
            { "Ballynahinch","Worcestershire"},
            { "Banbridge","Worcestershire"},
            { "Bangor","Worcestershire"},
            { "Carryduff","Worcestershire"},
            { "Castlewellan","Worcestershire"},
            { "Comber","County Antrim"},
            { "Donaghadee","County Antrim"},
            { "Doromore","County Antrim"},
            { "Downpatrick","County Antrim"},
            { "Dundonald","County Antrim"},
            { "Holywood","County Antrim"},
            { "Kilkeel","County Antrim"},
            { "Killyleagh","County Antrim"},
            { "Newcastle","County Antrim"},
            { "Newtownards","County Antrim"},
            { "Portaferry","County Antrim"},
            { "Rostrevor","County Antrim"},
            { "Saintfield","County Antrim"},
            { "Warrenpoint","County Antrim"},
            { "Enniskillen","County Antrim"},
            { "Lisnaskea","County Armagh"},
            { "Coleraine","County Armagh"},
            { "Derry","County Armagh"},
            { "Limavady","County Armagh"},
            { "Magherafelt","County Armagh"},
            { "Portstewart","County Armagh"},
            { "Castlederg","County Down"},
            { "Clogher","County Down"},
            { "Coalisland","County Down"},
            { "Cookstown","County Down"},
            { "Dungannon","County Down"},
            { "Fintona","County Down"},
            { "Fivemiletown","County Down"},
            { "Omagh","County Down"},
            { "Strabane","County Down"},
            { "Aberdeen","County Down"},
            { "Ballater","County Down"},
            { "Banchory","County Down"},
            { "Banff","County Down"},
            { "Banff and Macduff","County Down"},
            { "Boddam","County Down"},
            { "Clerkhill","County Down"},
            { "Ellon","County Down"},
            { "Fraserburgh","County Down"},
            { "Huntly","County Down"},
            { "Insch","County Down"},
            { "Inverbervie","County Fermanagh"},
            { "Inverurie","County Fermanagh"},
            { "Kemnay","County Londonderry"},
            { "Kintore","County Londonderry"},
            { "Laurencekirk","County Londonderry"},
            { "Macduff","County Londonderry"},
            { "Maud","County Londonderry"},
            { "Oldmeldrum","County Tyrone"},
            { "Peterhead","County Tyrone"},
            { "Portlethen","County Tyrone"},
            { "Portsoy","County Tyrone"},
            { "Red Cloak","County Tyrone"},
            { "Rosehearty","County Tyrone"},
            { "Stonehaven","County Tyrone"},
            { "Turriff","County Tyrone"},
            { "Westhill","County Tyrone"},
            { "Arbroath","Aberdeenshire"},
            { "Brechin","Aberdeenshire"},
            { "Carnoustie","Aberdeenshire"},
            { "Forfar","Aberdeenshire"},
            { "Kirriemuir","Aberdeenshire"},
            { "Monifieth","Aberdeenshire"},
            { "Montrose","Aberdeenshire"},
            { "Alloa","Aberdeenshire"},
            { "Alva","Aberdeenshire"},
            { "Clackmannan","Aberdeenshire"},
            { "Dollar","Aberdeenshire"},
            { "Menstrie","Aberdeenshire"},
            { "Tillicoultry","Aberdeenshire"},
            { "Tullibody","Aberdeenshire"},
            { "Annan","Aberdeenshire"},
            { "Castle Douglas","Aberdeenshire"},
            { "Dalbeattie","Aberdeenshire"},
            { "Dumfries","Aberdeenshire"},
            { "Gatehouse of Fleet","Aberdeenshire"},
            { "Gretna","Aberdeenshire"},
            { "Kelloholm","Aberdeenshire"},
            { "Kirkconnel","Aberdeenshire"},
            { "Kirkcudbright","Aberdeenshire"},
            { "Langholm","Aberdeenshire"},
            { "Lochmaben","Aberdeenshire"},
            { "Lockerbie","Aberdeenshire"},
            { "Moffat","Aberdeenshire"},
            { "Monreith","Aberdeenshire"},
            { "Newbridge Drive","Aberdeenshire"},
            { "Newton Stewart","Angus"},
            { "Sanquhar","Angus"},
            { "Stranraer","Angus"},
            { "Thornhill","Angus"},
            { "Wigtown","Angus"},
            { "Dundee","Angus"},
            { "Cockenzie and Port Seton","Angus"},
            { "Dunbar","Clackmannanshire"},
            { "Haddington","Clackmannanshire"},
            { "Musselburgh","Clackmannanshire"},
            { "North Berwick","Clackmannanshire"},
            { "Prestonpans","Clackmannanshire"},
            { "Tranent","Clackmannanshire"},
            { "Edinburgh?","Clackmannanshire"},
            { "Airth","Dumfries and Galloway"},
            { "Bo'ness","Dumfries and Galloway"},
            { "Bonnybridge","Dumfries and Galloway"},
            { "Borrowstounness","Dumfries and Galloway"},
            { "Carron","Dumfries and Galloway"},
            { "Denny","Dumfries and Galloway"},
            { "Duniplace","Dumfries and Galloway"},
            { "Dunmore","Dumfries and Galloway"},
            { "Falkirk","Dumfries and Galloway"},
            { "Grahamston","Dumfries and Galloway"},
            { "Grangemouth","Dumfries and Galloway"},
            { "Larbert","Dumfries and Galloway"},
            { "Stenhousemuir","Dumfries and Galloway"},
            { "Anstruther","Dumfries and Galloway"},
            { "Auchtermuchty","Dumfries and Galloway"},
            { "Balcurvie","Dumfries and Galloway"},
            { "Ballingry","Dumfries and Galloway"},
            { "Benarty","Dumfries and Galloway"},
            { "Buckhaven","Dumfries and Galloway"},
            { "Burntisland","Dumfries and Galloway"},
            { "Collydean","Dundee"},
            { "Cowdenbeath","East Lothian"},
            { "Crail","East Lothian"},
            { "Cupar","East Lothian"},
            { "Dalgety Bay","East Lothian"},
            { "Dunfermline","East Lothian"},
            { "Dysart","East Lothian"},
            { "East Wemyss","East Lothian"},
            { "Falkland","Edinburgh?"},
            { "Glenrothes","Falkirk"},
            { "Inverkeithing","Falkirk"},
            { "Kelty","Falkirk"},
            { "Kincardine","Falkirk"},
            { "Kinghorn","Falkirk"},
            { "Kinglassie","Falkirk"},
            { "Kirkcaldy","Falkirk"},
            { "Ladybank","Falkirk"},
            { "Letham","Falkirk"},
            { "Leuchars","Falkirk"},
            { "Leven","Falkirk"},
            { "Levenmouth","Falkirk"},
            { "Lochgelly","Falkirk"},
            { "Markinch","Fife"},
            { "Methil","Fife"},
            { "Newburgh","Fife"},
            { "Newport on Tay","Fife"},
            { "North Queensferry","Fife"},
            { "Pitcoudie","Fife"},
            { "Pittenweem","Fife"},
            { "Rosyth","Fife"},
            { "St Andrews","Fife"},
            { "St Monans","Fife"},
            { "Tayport","Fife"},
            { "Woodhaven","Fife"},
            { "Wormit","Fife"},
            { "Alness","Fife"},
            { "Aviemore","Fife"},
            { "Brora","Fife"},
            { "Cromarty","Fife"},
            { "Dingwall","Fife"},
            { "Dornoch","Fife"},
            { "Fort William","Fife"},
            { "Fortrose","Fife"},
            { "Grantown on Spey","Fife"},
            { "Invergordon","Fife"},
            { "Inverlochy","Fife"},
            { "Inverness","Fife"},
            { "Kingussie","Fife"},
            { "Mallaig","Fife"},
            { "Nairn","Fife"},
            { "Portree","Fife"},
            { "Tain","Fife"},
            { "Thurso","Fife"},
            { "Ullapool","Fife"},
            { "Wick","Fife"},
            { "Bathgate","Fife"},
            { "Dalkeith","Fife"},
            { "Edinburgh","Fife"},
            { "Linlithgow","Fife"},
            { "Loanhead","Fife"},
            { "Penicuik","Fife"},
            { "Buckie","Fife"},
            { "Cullen","Fife"},
            { "Dufftown","Fife"},
            { "Elgin","Highlands"},
            { "Forres","Highlands"},
            { "Keith","Highlands"},
            { "Lossiemouth","Highlands"},
            { "Aberfeldy","Highlands"},
            { "Auchterarder","Highlands"},
            { "Birnam","Highlands"},
            { "Blackford","Highlands"},
            { "Blair Atholl","Highlands"},
            { "Blairgowrie and Rattray","Highlands"},
            { "Bridge of Earn","Highlands"},
            { "Bridge of Tilt","Highlands"},
            { "Comrie","Highlands"},
            { "Coupar Angus","Highlands"},
            { "Crieff","Highlands"},
            { "Kinross","Highlands"},
            { "Perth","Highlands"},
            { "Pitlochry","Highlands"},
            { "Scone","Highlands"},
            { "Coldstream","Highlands"},
            { "Duns","Lothian"},
            { "Earlston","Lothian"},
            { "Eyemouth","Lothian"},
            { "Galashiels","Lothian"},
            { "Greenlaw","Lothian"},
            { "Hawick","Lothian"},
            { "Innerleithen","Lothian"},
            { "Jedburgh","Lothian"},
            { "Kelso","Lothian"},
            { "Lauder","Lothian"},
            { "Melrose","Moray"},
            { "Newtown St Boswells","Moray"},
            { "Peebles","Moray"},
            { "Selkirk","Moray"},
            { "Bridge of Allan","Moray"},
            { "Callander","Moray"},
            { "Doune","Moray"},
            { "Dunblane","Perth and Kinross"},
            { "Stirling","Perth and Kinross"},
            { "Airdrie","Perth and Kinross"},
            { "Ayr","Perth and Kinross"},
            { "Barrhead","Perth and Kinross"},
            { "Bearsden","Perth and Kinross"},
            { "Bellshill","Perth and Kinross"},
            { "Biggar","Perth and Kinross"},
            { "Campbeltown","Perth and Kinross"},
            { "Carluke","Perth and Kinross"},
            { "Clydebank","Perth and Kinross"},
            { "Coatbridge","Perth and Kinross"},
            { "Cumbernauld","Perth and Kinross"},
            { "Dumbarton","Perth and Kinross"},
            { "Dunoon","Perth and Kinross"},
            { "East Kilbride","Scottish Borders"},
            { "Glasgow","Scottish Borders"},
            { "Gourock","Scottish Borders"},
            { "Greenock","Scottish Borders"},
            { "Hamilton","Scottish Borders"},
            { "Helensburgh","Scottish Borders"},
            { "Inveraray","Scottish Borders"},
            { "Irvine","Scottish Borders"},
            { "Johnstone","Scottish Borders"},
            { "Kilbarchan","Scottish Borders"},
            { "Kilmarnock","Scottish Borders"},
            { "Kilwinning","Scottish Borders"},
            { "Lanark","Scottish Borders"},
            { "Largs","Scottish Borders"},
            { "Lochgilphead","Scottish Borders"},
            { "Maybole","Stirlingshire"},
            { "Milngavie","Stirlingshire"},
            { "Motherwell","Stirlingshire"},
            { "Oban","Stirlingshire"},
            { "Paisley","Stirlingshire"},
            { "Prestwick","Strathclyde"},
            { "Rothesay","Strathclyde"},
            { "Rutherglen","Strathclyde"},
            { "Saltcoats","Strathclyde"},
            { "Tobermory","Strathclyde"},
            { "Troon","Strathclyde"},
            { "Armadale","Strathclyde"},
            { "Ballencrieff","Strathclyde"},
            { "Blackridge","Strathclyde"},
            { "Bridgend","Strathclyde"},
            { "Broxburn","Strathclyde"},
            { "East Calder","Strathclyde"},
            { "Livingston","Strathclyde"},
            { "Stoneyburn","Strathclyde"},
            { "Whitburn","Strathclyde"},
            { "Kirkwall","Strathclyde"},
            { "Lerwick","Strathclyde"},
            { "Stornoway","Strathclyde"},
            { "Amlwch","Strathclyde"},
            { "Beaumaris","Strathclyde"},
            { "Benllech","Strathclyde"},
            { "Holyhead","Strathclyde"},
            { "Llanfairpwllgwyngyll","Strathclyde"},
            { "Llangefni","Strathclyde"},
            { "Menai Bridge","Strathclyde"},
            { "Ammanford","Strathclyde"},
            { "Burry Port","Strathclyde"},
            { "Carmarthen","Strathclyde"},
            { "Garnant","Strathclyde"},
            { "Glanamman","Strathclyde"},
            { "Kidwelly","Strathclyde"},
            { "Laugharne","Strathclyde"},
            { "Llandeilo","Strathclyde"},
            { "Llandovery","Strathclyde"},
            { "Llanelli","Strathclyde"},
            { "Newcastle Emlyn","Strathclyde"},
            { "St Clears","Strathclyde"},
            { "Whitland","Strathclyde"},
            { "Aberaeron","Strathclyde"},
            { "Aberystwyth","West Lothian"},
            { "Cardigan","West Lothian"},
            { "Lampeter","West Lothian"},
            { "Llandysul","West Lothian"},
            { "New Quay","West Lothian"},
            { "Tregaron","West Lothian"},
            { "Abergele","West Lothian"},
            { "Colwyn Bay","West Lothian"},
            { "Conwy","West Lothian"},
            { "Deganwy","West Lothian"},
            { "Llandudno","West Lothian"},
            { "Llandudno Junction","West Lothian"},
            { "Llanfairfechan","Western Isles"},
            { "Llanrwst","Western Isles"},
            { "Old Colwyn","Western Isles"},
            { "Penmaenmawr","Anglesey"},
            { "Towyn","Anglesey"},
            { "Carrog","Anglesey"},
            { "Corwen","Anglesey"},
            { "Denbigh","Anglesey"},
            { "Gellifor","Anglesey"},
            { "Llangollen","Anglesey"},
            { "Prestatyn","Carmarthenshire"},
            { "Rhuddlan","Carmarthenshire"},
            { "Rhyl","Carmarthenshire"},
            { "Ruthin","Carmarthenshire"},
            { "St Asaph","Carmarthenshire"},
            { "Bagallit","Carmarthenshire"},
            { "Buckley","Carmarthenshire"},
            { "Caerwys","Carmarthenshire"},
            { "Connah's Quay","Carmarthenshire"},
            { "Ewole","Carmarthenshire"},
            { "Flint","Carmarthenshire"},
            { "Hawarden","Carmarthenshire"},
            { "Holywell","Carmarthenshire"},
            { "Mold","Ceredigion"},
            { "Queensferry","Ceredigion"},
            { "Saltney","Ceredigion"},
            { "Shotton","Ceredigion"},
            { "Abertillery","Ceredigion"},
            { "Blaina","Ceredigion"},
            { "Brynmawr","Ceredigion"},
            { "Cwmbran","Conwy"},
            { "Ebbw Vale","Conwy"},
            { "Tafarnaubach","Conwy"},
            { "Tredegar","Conwy"},
            { "Bala","Conwy"},
            { "Barmouth","Conwy"},
            { "Betws y Coed","Conwy"},
            { "Blaenau Ffestiniog","Conwy"},
            { "Caernarfon","Conwy"},
            { "Criccieth","Conwy"},
            { "Dolgellau","Conwy"},
            { "Ffestiniog","Denbighshire"},
            { "Harlech","Denbighshire"},
            { "Llanberis","Denbighshire"},
            { "Llanfachreth","Denbighshire"},
            { "Nefyn","Denbighshire"},
            { "Porthmadog","Denbighshire"},
            { "Pwllheli","Denbighshire"},
            { "Tywyn","Denbighshire"},
            { "Y Felinheli","Denbighshire"},
            { "Aberdare","Denbighshire"},
            { "Caerphilly","Flintshire"},
            { "Llantrisant","Flintshire"},
            { "Maesteg","Flintshire"},
            { "Merthyr Tydfil","Flintshire"},
            { "Pontypridd","Flintshire"},
            { "Porth","Flintshire"},
            { "Porthcawl","Flintshire"},
            { "Abergavenny","Flintshire"},
            { "Caldicot","Flintshire"},
            { "Chepstow","Flintshire"},
            { "Monmouth","Flintshire"},
            { "Usk","Flintshire"},
            { "Fishguard","Flintshire"},
            { "Goodwick","Gwent"},
            { "Hakin","Gwent"},
            { "Haverfordwest","Gwent"},
            { "Milford Haven","Gwent"},
            { "Narberth","Gwent"},
            { "Neyland","Gwent"},
            { "Pembroke","Gwent"},
            { "Pembroke Dock","Gwent"},
            { "St Davids","Gwynedd"},
            { "Tenby","Gwynedd"},
            { "Brecon","Gwynedd"},
            { "Builth Wells","Gwynedd"},
            { "Cefnllys","Gwynedd"},
            { "Crickhowell","Gwynedd"},
            { "Hay on Wye","Gwynedd"},
            { "Knighton","Gwynedd"},
            { "Llandrindod Wells","Gwynedd"},
            { "Llanfair Caereinion","Gwynedd"},
            { "Llanfyllin","Gwynedd"},
            { "Llangors","Gwynedd"},
            { "Llanidloes","Gwynedd"},
            { "Llanwrtyd Wells","Gwynedd"},
            { "Machynlleth","Gwynedd"},
            { "Montgomery","Gwynedd"},
            { "Newtown","Gwynedd"},
            { "Old Radnor","Gwynedd"},
            { "Presteigne","Gwynedd"},
            { "Rhayader","Gwynedd"},
            { "Talgarth","Mid Glamorgan"},
            { "Welshpool","Mid Glamorgan"},
            { "Barry","Mid Glamorgan"},
            { "Cardiff","Mid Glamorgan"},
            { "Cowbridge","Mid Glamorgan"},
            { "Llantwit Major","Mid Glamorgan"},
            { "Penarth","Mid Glamorgan"},
            { "Gorseinon","Mid Glamorgan"},
            { "Lliw Valey","Mid Glamorgan"},
            { "Neath","Monmouthshire"},
            { "Port Talbot","Monmouthshire"},
            { "Swansea","Monmouthshire"},
            { "Chirk","Monmouthshire"},
            { "Overton on Dee","Monmouthshire"},
            { "Rhosllannerchrugog","Pembrokeshire"},
            { "Rhosnesni","Pembrokeshire"},
            { "Wrexham","Pembrokeshire"},
        };
    }
}
