//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFactory.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataFactory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com,net,co.uk,org,org.uk.
        /// </summary>
        internal static string EmailDomains {
            get {
                return ResourceManager.GetString("EmailDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer,HRAssistant,MarketingManager,AccountManager,PayrollClerk,ProjectManager,BusinessAnalyst,ProductManager,SoftwareDeveloper,WebDeveloper,SystemsAdministrator,SupportEngineer,Accountant,SeniorAccountant,Controller,Technician,Trainee,Receptionist,AssistantManager,OfficeManager.
        /// </summary>
        internal static string JobTitles {
            get {
                return ResourceManager.GetString("JobTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeman,Jefferson,Washington,Wheeler,Martz,Hudson,Smith,Johnson,Williams,Black,Bradley,Jones,Brown,Davis,Cooke,Cunningham,Wilson,Moore,Taylor,Anderson,Thomas,Jackson,White,Harris,Thompson,Garcia,Gordon,Martinez,Robinson,Clark,Welsh,Rodriguez,Meyers,Lewis,Lee,Walker,Martin,Hall,Allen,Murphy,Murray,Young,Hernandez,King,Wright,Perry,Hill,Scott,Green,Adams,Baker,Cartwright,Mitchell,Roberts,Turner,Phillips,Campbell,Parker,Evans,Edwards,Collins,Morris,Rodgers,Reed,Cook,Morgan,Bell,Bailey,Cooper,Richardson,Cox,War [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emily,Molly,Sophie,Jessica,Amy,Abigail,Abby,Lauren,Holly,Kate,Lucy,Elizabeth,Leah,Emma,Helen,Mary,Lisa,Elizabeth,Jennifer,Susan,Karen,Helen,Sandra,Donna,Carol,Sharon,Michelle,Laura,Sarah,Kim,Jessica,Cynthia,Angela,Melissa,Amy,Anne,Rebecca,Kate,Amanda,Stephanie,Christine,Janet,Catharine,Diane,Alice,Julie,Heather,Jill,Joan,Judy,Ashley,Kelly,Nicole,Denise,Jane,Laurie,Rachel,Andrea,Marilyn,Bonnie,Tina,Emily,Dawn,Tracy,Tiffany,Wendy,Shannon,Carrie,April,Jamie,Megan,Erin,Sally,Erica,Stacy,Brittany.
        /// </summary>
        internal static string NamesFemale {
            get {
                return ResourceManager.GetString("NamesFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shane,Rob,Brad,Cameron,Chris,Neal,Jordan,Charlie,Jeff,Caleb,Eric,Samuel,Cory,Neil,Shaun,Nat,Calvin,Bob,James,Joe,Toby,Andy,Gary,Ruben,Matt,Geoff,Sidney,William,Tariq,Christian,Donny,Tim,Ben,Ross,Stephen,Duane,Flynn,Jake,Greg,David,Arthur,Mickey,Daniel,Brian,Mike,Chase,Jeremy,Sam,Nick,Alex,Tom,Landon,Jack,Derek,Jack,Oliver,Harry,Thomas,William,James,Charles,Daniel,Richard,Lewis,George,Adam,Ben,Owen,Paul.
        /// </summary>
        internal static string NamesMale {
            get {
                return ResourceManager.GetString("NamesMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odin,Papa Bear,Yeti,Moose,Kong,Nero,Buster,Mack,Tank,Kingpin,Boom Boom,Richter,Dozer,Sledge,Brick,Crater,Flash,Nova,Smokey,Thunder,Arcade,Casino,Disco,Crash,Doomsday,Nuke,Road Block,Collateral,Tectonic,Strobe,Diesel,Hulk,Prototype,Lights Out,Rascal,Cash,Duke,Viking,Nitro,Mad Man,Bull,Cowboy,Spike,Tombstone,Gonzo,DJ,Zilch,Hazard,Bonzai,Geronimo,Septic,Chops,Coney,Devil Dog,Trips,Spitfire,Loco,Blitz,Dice,Cobra,Wolverine,Socks,Caper,Gunner,Shotsy,Boomer,D.O.A.,Android,Desperado,Psycho,Twitch,Pitbull,Mad Dog,Rh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NickNames {
            get {
                return ResourceManager.GetString("NickNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ltd,PLC,Corp.,LLP,Limited,Inc.,plc,Co.,NPO.
        /// </summary>
        internal static string OrganisationCompanySuffixes {
            get {
                return ResourceManager.GetString("OrganisationCompanySuffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturers,Solutions,Services,Entertainment,Media,Group,Productions,Technologies,Systems,Airways,Electronics,Appliances,Instruments,Communications,Studios,Associates,Communications,Foundation,Games,Publishing,Institute,International,Works,Laboratories,Digital,Energy.
        /// </summary>
        internal static string OrganisationNameDescriptions {
            get {
                return ResourceManager.GetString("OrganisationNameDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft,Google,Apple,Dell,Intel,Samsung,LG,Red River Software,University of Sussex,Cadbury,Pepsi,BBC,Facebook,CityLink,Spotify,Valve,Electronic Arts,Costa.
        /// </summary>
        internal static string Organisations {
            get {
                return ResourceManager.GetString("Organisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple,Carpenters,Cherry,Bishops,Summerfield,Charlwood,Albany,Worthing,Pleasant,Orchard,Butcher,Lexington,Grovesnor,Church,London,Oxford,St. Johns,High,Station,Main,Park,Victoria,Green,Manor,Queens,New,Grange,Kings,Windsor,Highfield,York,Mill,Geirge,Springfield,Albert,Alexander,Stanley,Chester,Richmond.
        /// </summary>
        internal static string StreetNames {
            get {
                return ResourceManager.GetString("StreetNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avenue,Crescent,Mews,Road,Street,Cross,Meadow,Towers,Lane,Way.
        /// </summary>
        internal static string StreetTypes {
            get {
                return ResourceManager.GetString("StreetTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrs,Miss,Ms.
        /// </summary>
        internal static string TitlesFemale {
            get {
                return ResourceManager.GetString("TitlesFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr.
        /// </summary>
        internal static string TitlesMale {
            get {
                return ResourceManager.GetString("TitlesMale", resourceCulture);
            }
        }
    }
}
